package classes;

public enum PlayerStates {
    DEFAULT,
    STARTGAME,
    SETPLAYER,
    ROUNDSTARTED,
    SPINWHEEL,
    READYTOSPIN,
    TOSPIN,
    GETRESULT,
    SHOWHEELRESULT,
    CONTINUETURN,
    CHANGETURN,
    CHECKLETTER,
    FINISHCHECK,
    SHOWVOCAL,
    VOCALSHOWED,
    ROUNDEND,
    STARTNEWROUND;
}
